### ISSUE TITLE
Commit failing / sass lint failing

### ISSUE THREAD

**Issue by julian-gernun** [SUI-Components/SUIStudio#58]
node version: 6.10.1
npm version: 4.2.0

`> npm run lint:sass`

Console output:
```
src/components/demo/_style.scss
  30:4   warning  Class '.codeMirror' should match regular expression /^(?:[a-zA-Z0-9]*)\-[A-Z]{1}[a-z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$/         class-name-format
  38:6   warning  Class '.codeMirror-scroll' should match regular expression /^(?:[a-zA-Z0-9]*)\-[A-Z]{1}[a-z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$/  class-name-format
  42:6   warning  Class '.codeMirror-sizer' should match regular expression /^(?:[a-zA-Z0-9]*)\-[A-Z]{1}[a-z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$/   class-name-format
  43:29  warning  !important not allowed                                                                                                                                        no-important
  44:23  warning  !important not allowed                                                                                                                                        no-important
  45:23  warning  !important not allowed                                                                                                                                        no-important

src/components/navigation/_style.scss
  15:14  warning  Hex values should use the long-form format - 6 characters                      hex-length
  15:14  warning  Color literals such as '#333' should only be used in variable declarations     no-color-literals
  31:12  warning  Hex values should use the long-form format - 6 characters                      hex-length
  31:12  warning  Color literals such as '#666' should only be used in variable declarations     no-color-literals
  50:30  warning  Color literals such as '#e4e4e4' should only be used in variable declarations  no-color-literals
  56:1   warning  Space expected between blocks                                                  empty-line-between-blocks
  57:27  warning  Color functions such as 'rgba' should only be used in variable declarations    no-color-literals
  61:1   warning  Space expected between blocks                                                  empty-line-between-blocks
  62:27  warning  Color functions such as 'rgba' should only be used in variable declarations    no-color-literals

src/components/preview/_style.scss
  3:23  warning  Color literals such as '#c10000' should only be used in variable declarations  no-color-literals
  4:12  warning  Color literals such as '#f0f0f0' should only be used in variable declarations  no-color-literals

src/styles/_settings.scss
   2:13  warning  Hex values should use the long-form format - 6 characters  hex-length
  72:14  warning  Hex values should use the long-form format - 6 characters  hex-length

src/styles/components/_tabs.scss
  70:25  warning  Color functions such as 'rgba' should only be used in variable declarations  no-color-literals
  76:25  warning  Color functions such as 'rgba' should only be used in variable declarations  no-color-literals

✖ 21 problems (0 errors, 21 warnings)
```

Npm log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/julian.gernun/.nvm/versions/node/v6.10.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint:sass' ]
2 info using npm@4.2.0
3 info using node@v6.10.1
4 verbose run-script [ 'prelint:sass', 'lint:sass', 'postlint:sass' ]
5 info lifecycle @schibstedspain/sui-studio@3.4.0~prelint:sass: @schibstedspain/sui-studio@3.4.0
6 silly lifecycle @schibstedspain/sui-studio@3.4.0~prelint:sass: no script for prelint:sass, continuing
7 info lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: @schibstedspain/sui-studio@3.4.0
8 verbose lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: unsafe-perm in lifecycle true
9 verbose lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/julian.gernun/projects/ij/SUIStudio/node_modules/.bin:/Users/julian.gernun/.jenv/shims:/Users/julian.gernun/.jenv/bin:/Users/julian.gernun/bin:/usr/local/bin:/Users/julian.gernun/.nvm/versions/node/v6.10.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin
10 verbose lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: CWD: /Users/julian.gernun/projects/ij/SUIStudio
11 silly lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: Args: [ '-c', 'linting-rules sass' ]
12 silly lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: Returned: code: 1  signal: null
13 info lifecycle @schibstedspain/sui-studio@3.4.0~lint:sass: Failed to exec lint:sass script
14 verbose stack Error: @schibstedspain/sui-studio@3.4.0 lint:sass: `linting-rules sass`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @schibstedspain/sui-studio@3.4.0
16 verbose cwd /Users/julian.gernun/projects/ij/SUIStudio
17 error Darwin 16.6.0
18 error argv "/Users/julian.gernun/.nvm/versions/node/v6.10.1/bin/node" "/usr/local/bin/npm" "run" "lint:sass"
19 error node v6.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error @schibstedspain/sui-studio@3.4.0 lint:sass: `linting-rules sass`
23 error Exit status 1
24 error Failed at the @schibstedspain/sui-studio@3.4.0 lint:sass script 'linting-rules sass'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the @schibstedspain/sui-studio package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     linting-rules sass
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs @schibstedspain/sui-studio
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls @schibstedspain/sui-studio
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by miduga** [comment]
Could you try with the `npm` version 3? It's weird as all of them are warnings and that shouldn't stop the commit process.

**Comment by julian-gernun** [comment]
Yep, I tried v3.10.10 and same result.

**Comment by carlosvillu** [comment]
Right now if there is any kind of output you will get an error. 

Please change this behavior here and release a new version. 

https://github.com/SUI-Components/frontend-pre-commit-rules/blob/master/packages/linting-rules/bin/linting-rules-sass.js

Enviado desde mi iPhone

**Comment by julian-gernun** [comment]
I'm not sure what we want. I see 2 options:
- Do we want to **always** ignore warnings? 
- Do we want some kind of **strict mode** to make it possible to fail on warnings? This solution would consist in creating another sass-lint.yml config file like explained in here https://github.com/sasstools/sass-lint/issues/1012

**Comment by naxhh** [comment]
Maybe is easier and you just need to check the child exit code? if is smart enough it will return 0 always and >1 when there is an error.

You can check error codes running:

```
$ sass-lint -c ... . .. . 

$ echo $?

**Comment by julian-gernun** [comment]
With any of the solution you propose, there will be no output in the console and the developer won't see the linter has detected XX warnings message. I'm afraid that sooner or later we'll end up having a lot of warnings because of devs like me that do not run npm run lint:sass before commiting. 

PR https://github.com/SUI-Components/frontend-pre-commit-rules/pull/35
